version: '3s'

services:
  web:
    build: .

    depends_on:
      - db
    
    volumes:
      - ./:/code:ro

    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=octavio
      - POSTGRES_DB=fastapi_docker_pgsql

volumes:
  postgres_data: